### PR TITLE
Add lambda, Step Function and SQS handlers

### PR DESCRIPTION
**Pull request by similark**

### CODE REVIEW

**Comment by similark** [comment]
review plz?? @MacLikorne

**Comment by evoxmusic** [comment]
thanks @similark for the PR 🙏

**Comment by MacLikorne** [comment]
> review plz?? @MacLikorne

Sorry I missed the PR.

Could you please also add new features to README (AWS features list + new flags in command line) ?

For the version, since it's brand new features, you can set it to 0.11.0.

Thx for the contribution !!!

**Review by MacLikorne — APPROVED** [review]

**Comment by similark** [comment]
Not sure what happened with the repeating conflicts - but what's the status on this? @MacLikorne

**Comment by cregev** [comment]
@MacLikorne any chance you will help @similark merge it?

**Comment by MacLikorne** [comment]
> @MacLikorne any chance you will help @similark merge it?

Gonna go it this week @cregev

**Review by MacLikorne — APPROVED** [review]

**Comment by MacLikorne** [comment]
@similark @cregev conflicts solved. Merging the branch and doing a release.

Thx for the contribution.

**Pull request merged**
